apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: california-model
  namespace: kubeflow-user01  # 본인 네임스페이스로 변경
  annotations:
    autoscaling.knative.dev/minScale: "1"
    autoscaling.knative.dev/maxScale: "3"
spec:
  predictor:
    sklearn:
      # MinIO 경로 사용
      storageUri: "s3://mlflow-artifacts/2/artifacts/model"
      # MinIO 자격 증명
      env:
      - name: AWS_ACCESS_KEY_ID
        value: "minio"
      - name: AWS_SECRET_ACCESS_KEY
        value: "minio123"
      - name: AWS_ENDPOINT_URL
        value: "http://minio-service.kubeflow.svc:9000"
      - name: S3_USE_HTTPS
        value: "0"
      - name: S3_VERIFY_SSL
        value: "0"
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
